export const information = [
    {
      id: 1,
      title: 'Styled-Components 소개하기',
      content: 'Styled Component란 자바스크립트 파일 내에서 CSS를 사용할 수 있게 해주는 대표적인 CSS-in-JS 라이브러리로 리액트개발에서 주로 사용되는 라이브러리이다. React, Vue, Angular 등과 같은 프레임워크, 라이브러리들이 인기를 끌면서 웹 개발의 패러다임이 바뀌게 되었다. 이들은 웹 페이지를 여러 개의 컴포넌트로 분리하고, 각 컴포넌트에 HTML, CSS, 자바스크립트를 종합하는 패턴으로 구성하는 컴포넌트 기반 개발 방법을 주류로 올려놓게 되었다. 따라서 CSS 방식에서도 CSS-module 등을 사용하여 CSS 파일을 외부로 분리하는 방법이 아닌 Styled Component를 사용하여 자바스크립트 파일 안에 삽입하는 CSS-in-JS 방식이 트렌드가 되었다.Styled Component를 사용하면 컴포넌트 자체에 특정 스타일링을 할 수 있기 때문에 재사용성을 더 높일 수 있고, 자바스크립트에 영향을 받는 스타일링을 더욱 간편하게 구현할 수 있다.',
      imageUrl: '../images/posts/component.png',
      date: '2023.07.18',
      comment: '99개의 댓글',
      userName: '웨이드',
      profileImageUrl: '../images/profile/웨이드.jpg',
      likes: '9999',
    },
    {
      id: 2,
      title: 'React-Router-Dom 소개하기',
      content: '리액트를 사용할 때 페이지를 이동할 때 필요한 라이브러리이다. 원래는 A페이지를 보여주고 싶다면 A.html파일을 이용하고 B페이지를 보여주고 싶다면 B.html 파일을 보여주는 방식이었다. 하지만 리액트에서는 웹 사이트의 전체 페이지를 하나의 페이지에 담아 동적으로 화면을 바꿔가며 표현한다. 이것을 SPA(Single Page Application) 이라고 부른다. SPA에서는 어떻게 페이지 전환(브라우징)을 해줄까? 이것은 HTML 5의 History API를 사용해서 가능하게 만든다. 자바스크립트 영역에서 History API를 이용해 현재 페이지 내에서 페이지 이동이 일어난 것 처럼 보여준다.',
      imageUrl: '../images/posts/Router.png',
      date: '2023.07.18',
      comment: '99개의 댓글',
      userName: '엠버',
      profileImageUrl: '../images/profile/엠버.jpg',
      likes: '9999',
    },
    {
      id: 3,
      title: '노마드 코더-REACT HOOK',
      content:'useTitle: react document의 title을 몇개의 hooks와 함께 바꿈// useInput: input 역할//usePageLeave: 유저가 page를 벗어나는 시점 발견하고 함수 실행함//useClick: 누군가 element 클릭하는 시점을 발견//useFadeIn: 애니메이션을 element 안으로 서서히 사라지게함//useFullscreen: 어떤 element든 풀스크린으로 만들거나 일반화면으로 돌아가게 함//useHover: 마우스를 올렸을 때 감지//useNetwork: online, offline 확인//useNotification: notification API 사용할 때 유저에게 알림 전송//useScroll: 스크롤 감지//useTabs: 웹사이트에 메뉴 또는 무엇이든간에 tab을 사용하기 쉬움//usePreventLeave: 유저가 변경사항이나 무엇이든간에 저장하지 않고 페이지를 벗어나길 원할 때 확인//',
      imageUrl: '../images/posts/nomad.png',
      date: '2023.07.18',
      comment: '99개의 댓글',
      userName: '공기',
      profileImageUrl: '../images/profile/공기.jpg',
      likes: '9999',
    },
  ];